version: "3.7"

services:
  upsnap:
    image: seriousm4x/upsnap:latest
    container_name: upsnap
    restart: unless-stopped
    ports:
      - "3000:3000"
    network_mode: host
    volumes:
      - upsnap-data:/app/data

volumes:
  upsnap-data:
